name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install
      - name: Build client
        run: |
          cd client
          npm run build
        env:
          CI: false
      - name: Build server
        run: |
          cd server
          npm run build
        env:
           CI: false
      - name: Deploy to Heroku
        env:
          TOKEN: ${{ secrets.HEROKU_TOKEN }}
          APP: ${{ secrets.HEROKU_APP }}
        run: |
          git remote add heroku https://heroku:$TOKEN@git.heroku.com/$APP.git
          git push heroku HEAD:main -f
