name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Navigaet to client
        run: cd ./client
      - name: Install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: Navigaet to server
        run: cd ../server
      - name: Install dependencies
        run: npm install
      - name: build
        run: npm run build